[package]
name = "mock-program"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
solana-program = "1.10"

[lib]
name = "mock_program"
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []